# Generated by Django 2.2.9 on 2019-12-21 00:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name'], 'verbose_name': 'organizacja', 'verbose_name_plural': 'organizacje'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='opis organizacji'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='lokalizacja / miasto'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa organizacji'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='właściciel'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='private',
            field=models.BooleanField(default=False, verbose_name='organizacja prywatna'),
        ),
    ]
