# Generated by Django 2.2.9 on 2019-12-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191221_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='opis organizacji'),
        ),
    ]
