# Generated by Django 2.2.9 on 2019-12-21 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191221_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcategory',
            options={'verbose_name': 'kategoria klubów', 'verbose_name_plural': 'kategorie klubów'},
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['name'], 'verbose_name': 'sezon rozgrywek', 'verbose_name_plural': 'sezony rozgrywek'},
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='clubcategory',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='clubcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_categories', to='dashboard.Organization', verbose_name='organizacja'),
        ),
        migrations.AlterField(
            model_name='clubcategory',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.ClubCategory', verbose_name='kategoria nadrzędna'),
        ),
        migrations.AlterField(
            model_name='season',
            name='double_year',
            field=models.BooleanField(default=True, verbose_name='rozgrywki w dwóch latach'),
        ),
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa sezonu'),
        ),
        migrations.AlterField(
            model_name='season',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seasons', to='dashboard.Organization', verbose_name='organizacja'),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_year',
            field=models.IntegerField(verbose_name='rok rozpoczęcia'),
        ),
    ]
