# Generated by Django 2.2.9 on 2019-12-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191221_1142'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='clubcategory',
            unique_together={('organization', 'parent', 'name')},
        ),
    ]
