# Generated by Django 2.2.9 on 2020-01-01 03:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191222_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubcategory',
            options={'verbose_name': 'kategoria klubów', 'verbose_name_plural': 'kategorie klubów'},
        ),
        migrations.AlterField(
            model_name='club',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='dashboard.ClubCategory', verbose_name='kategoria'),
        ),
        migrations.AlterUniqueTogether(
            name='clubcategory',
            unique_together=set(),
        ),
    ]
