# Generated by Django 2.2.9 on 2020-01-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20200101_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clubs', to='dashboard.Country', verbose_name='kraj'),
        ),
        migrations.AlterField(
            model_name='club',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='opis'),
        ),
        migrations.AlterField(
            model_name='club',
            name='founded',
            field=models.IntegerField(blank=True, null=True, verbose_name='rok założenia'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=50, verbose_name='nazwa klubu'),
        ),
        migrations.AlterField(
            model_name='club',
            name='national',
            field=models.BooleanField(default=False, verbose_name='reprezentacja kraju'),
        ),
        migrations.CreateModel(
            name='TeamCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa kategorii')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_categories', to='dashboard.Organization', verbose_name='organizacja')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dashboard.TeamCategory', verbose_name='kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'kategoria zespołów',
                'verbose_name_plural': 'kategorie zespołów',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='pełna nazwa zespołu')),
                ('short_name', models.CharField(blank=True, max_length=25, null=True, verbose_name='krótka nazwa zespołu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='opis')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='dashboard.TeamCategory', verbose_name='kategoria')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='dashboard.Club', verbose_name='klub')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='dashboard.Season', verbose_name='sezon')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
