# Generated by Django 2.2.9 on 2020-01-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200101_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nazwa kategorii')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_categories', to='dashboard.Organization', verbose_name='organizacja')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dashboard.GameCategory', verbose_name='kategoria nadrzędna')),
            ],
            options={
                'verbose_name': 'kategoria rozgrywek',
                'verbose_name_plural': 'kategorie rozgrywek',
            },
        ),
    ]
