# Generated by Django 2.2.9 on 2020-01-05 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_gamecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='club',
            unique_together={('category', 'name')},
        ),
    ]
