# Generated by Django 2.2.9 on 2020-01-05 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200105_1305'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('category', 'season', 'name')},
        ),
    ]
