# Generated by Django 2.2.9 on 2020-01-05 16:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0012_auto_20200105_1315'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('owner', 'name')},
        ),
    ]
