# Generated by Django 2.2.9 on 2019-12-20 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('users', '0002_auto_20191220_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_country',
            field=models.ForeignKey(default=179, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Country'),
            preserve_default=False,
        ),
    ]
