# Generated by Django 2.2.9 on 2019-12-20 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_default_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Country'),
        ),
    ]
