# Generated by Django 2.2.9 on 2019-12-21 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191220_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'użytkownik', 'verbose_name_plural': 'użytkownicy'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='default_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Country', verbose_name='domyślny kraj'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adres e-mail'),
        ),
    ]
