# Generated by Django 2.2.9 on 2019-12-31 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191231_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='default_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='dashboard.Country', verbose_name='domyślny kraj'),
        ),
    ]
