# Generated by Django 2.2.9 on 2020-01-05 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0009_gamecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('up_to_sets', models.SmallIntegerField(choices=[(2, 2), (3, 3)], verbose_name='do ilu setów')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='dashboard.GameCategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='ScoringSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_up_to', models.SmallIntegerField(choices=[(2, 2), (3, 3)], default=3)),
                ('name', models.CharField(max_length=50)),
                ('result_3_0', models.SmallIntegerField(blank=True, default=0)),
                ('result_3_1', models.SmallIntegerField(blank=True, default=0)),
                ('result_3_2', models.SmallIntegerField(blank=True, default=0)),
                ('result_2_3', models.SmallIntegerField(blank=True, default=0)),
                ('result_1_3', models.SmallIntegerField(blank=True, default=0)),
                ('result_0_3', models.SmallIntegerField(blank=True, default=0)),
                ('result_2_0', models.SmallIntegerField(blank=True, default=0)),
                ('result_2_1', models.SmallIntegerField(blank=True, default=0)),
                ('result_1_2', models.SmallIntegerField(blank=True, default=0)),
                ('result_0_2', models.SmallIntegerField(blank=True, default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='volleyball_scoring_systems', to='dashboard.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.SmallIntegerField()),
                ('host_sets', models.SmallIntegerField()),
                ('guest_sets', models.SmallIntegerField()),
                ('set_1_host', models.SmallIntegerField()),
                ('set_1_guest', models.SmallIntegerField()),
                ('set_2_host', models.SmallIntegerField()),
                ('set_2_guest', models.SmallIntegerField()),
                ('set_3_host', models.SmallIntegerField(blank=True, null=True)),
                ('set_3_guest', models.SmallIntegerField(blank=True, null=True)),
                ('set_4_host', models.SmallIntegerField(blank=True, null=True)),
                ('set_4_guest', models.SmallIntegerField(blank=True, null=True)),
                ('set_5_host', models.SmallIntegerField(blank=True, null=True)),
                ('set_5_guest', models.SmallIntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField()),
                ('order', models.SmallIntegerField()),
                ('finished', models.BooleanField(default=False)),
                ('walkover', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='volleyball.Game')),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_team', to='dashboard.Team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='host_team', to='dashboard.Team')),
            ],
            options={
                'ordering': ['round', 'order'],
            },
        ),
        migrations.AddField(
            model_name='game',
            name='scoring_system',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='games', to='volleyball.ScoringSystem'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='games', to='dashboard.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(related_name='games', to='dashboard.Team'),
        ),
    ]
