# Generated by Django 2.2.9 on 2020-01-05 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='organization',
        ),
    ]
